/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'media',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      sans: [
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      serif: [
        'ui-serif',
        'Georgia',
        'Cambria',
        'Times New Roman',
        'Times',
        'serif',
      ],
      mono: [
        'ui-mono',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        'Liberation Mono',
        'Courier New',
        'monospace',
      ],
      mediumSerifItalic: ['CharterItalic'],
      mediumSerif: ['Charter'],
      'workSansThin': ['WorkSans-Thin'],
      'workSansLight': ['WorkSans-Light'],
      'workSansRegular': ['WorkSans-Regular'],
      'workSansSemiBold': ['WorkSans-SemiBold'],
      'workSansBold': ['WorkSans-Bold'],
    },
    screens: {
      'xlarge': {'max': '1500px'},
      'lrge': {'max': '1300'},
      'med': {'max': '1100'},
      'sm': {'max': '984'},
      'xsm': {'max': '700'},
      'tiny': {'max': '500'},
    },
    extend: {
    },
  },
  plugins: [],
}
